name: Build Images

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: hashim12
          password: RockennY12!
      
      - name: Build and push api-gateway image
        uses: docker/build-push-action@v3
        with:
          files: |
            api-gateway/Dockerfile
          context: api-gateway
          push: true
          tags: hashim12/cafe-management-system-api-gateway:latest
        run: |
          docker build -t hashim12/cafe-management-system-api-gateway:latest -f api-gateway/Dockerfile .
          docker push hashim12/cafe-management-system-api-gateway:latest

      - name: Build and push customer-service image
        uses: docker/build-push-action@v3
        with:
          files: |
            customer-services/Dockerfile
          context: customer-services
          push: true
          tags: hashim12/cafe-management-system-customer-services:latest
        run: |
          docker build -t hashim12/cafe-management-system-customer-services:latest -f customer-services/Dockerfile .
          docker push hashim12/cafe-management-system-customer-services:latest

      - name: Build and push order-service image
        uses: docker/build-push-action@v3
        with:
          files: |
            order-services/Dockerfile
          context: order-services
          push: true
          tags: hashim12/cafe-management-system-order-services:latest
        run: |
          docker build -t hashim12/cafe-management-system-order-services:latest -f order-services/Dockerfile .
          docker push hashim12/cafe-management-system-order-services:latest

      